
trigger:
- master
variables:
 -name: agent.preferPowerShellOnConatiners
 Value : 'True'

pool:
  vmImage: Windows-latest
container:
  image: techmuipathroot.azurecr.io/uipathrobot:59
  endpoint: techmuipathroot

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    orchestratorConnection: 'Username_Uipath_Connection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'  
- publish: '$(Build.ArtifactStagingDirectory)\Output' 
  artifact: drop

  
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'Username_Uipath_Connection'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Default'
    environments: 'Dev'
    entryPoints: 'Main.xaml'