

trigger:
- master
variables:
 -name: agent.preferPowerShellOnConatiners
 Value : 'True'

pool:
  vmImage: Windows-latest
container:
  image: techmuipathroot.azurecr.io/uipathrobot:59
  endpoint: techmuipathroot

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

-